### ISSUE TITLE
Symbol and Footprint for Encoder?

### ISSUE THREAD

**Issue by m-r-m-s** [Deftaudio/MacroPot#4]
Hi, 

Is the Bourns switch encoder symbol and footprint available a custom one you made or is that available somewhere else?

I haven't been able to track it down yet. Looks like I might be able to download the symbol from mouser but I don't have a windows based computer at the moment. Thanks!

**Comment by Deftaudio** [comment]
Just design one yourself. This is not difficult. I'm using KiCad for this project and I uploaded my own in a files section: https://github.com/Deftaudio/MacroPot/tree/master/Schematics/Footprints

**Comment by m-r-m-s** [comment]
Ok, thank you. I am new to kiCad so I really appreciate you sharing the footprint and will take on the challenge of designing one myself =)
