### ISSUE TITLE
Arduino file settings 

### ISSUE THREAD

**Issue by machinehistories** [Deftaudio/MacroPot#6]
First off I am glad I finally built your device it’s a very smart thing and so well documented. In your example arduino file you have all of the macro settings commented out. If I uncomment those lines and upload the file those settings don’t appear to load. For example none of the names are displayed on the Oled. Can you tell me what to do to add macro settings using the commented code in arduino or is the only option to use sysex. Thanks

**Comment by Deftaudio** [comment]
Hi Jason, that's easy to sort out. You don't need to change the code. Just after initial programming load the default macro set. It's here in scripts https://github.com/Deftaudio/MacroPot/tree/master/SysEx%20scripts and the details are in the video guide.

**Comment by machinehistories** [comment]
I got it working well with sysex as shown in the video but if I wanted to
use arduino instead of sysex is that possible? It looks like you have a
section of code commented out that appears to set the button and
controllers but when I uncommented it and uploaded the code it didn't
appear to take the settings from the arduino code. I was just curious. It's
a very neat device.

**Comment by Deftaudio** [comment]
I see. Those line were left from some development where I didn't want to touch EPROM memory each time and kept it in constants for the simplicity. Since that time many code has been added, including reading and writing to EPROM, so I'm not surprised that it's no longer working. It's better to program it through SysEx, it updates all data structures in EPROM.

**Comment by machinehistories** [comment]
Gotcha. thanks. I made a spreadsheet to automate the generation of the
sysex argument. It might be useful to others to help get their arguments
formatted. Feel free to share it. thanks
 [image: macro.jpg]

**Comment by Deftaudio** [comment]
Please, share. Another user made an attempt for MAX patch, however I found it broken and don't have MAX license to fix it.

**Comment by machinehistories** [comment]
I uploaded it to a repository since it didn't seem to keep the attachment in my previous response.[https://github.com/machinehistories/macropt_sysex_sheet](url)

**Comment by Deftaudio** [comment]
Thank you, added to the SysEx Scripts directory.

**Comment by machinehistories** [comment]
that's pretty cool. thanks

**Comment by machinehistories** [comment]
I am trying to add 6 controllers. I want to be able to have one mixer
channel on the tx-6 raise in volume and the others lower. You can cc
control the faders. I tried modifying the arduino code and then adding a
macro with 6 controllers. When I check the midi output controller 1 is
double the values output on controllers 3-6 even though they should all be
the same. Controller 2 is not outputting a message but at a certain point
controller one stops outputting a value and controller 2 starts outputting
but then controller 1 no longer outputs. I'm sure you can tell me what I
did wrong. I'm not a programmer and aside from changing the obvious
settings in the code like the max number of controllers from 5 to 6 I'm not
sure what else I should change. I'd really appreciate your help. Also what
curve value do you recommend for volume control.  thanks

**Comment by machinehistories** [comment]
I think I got it working but I had to change the max number of macros to 8.
Is this because of the eprom memory limit?

**Comment by Deftaudio** [comment]
I'm sorry, it's been years since I touched that code. 
You may have just a dirty EPROM. When you increased a max macros #, it tries to read it from EPROM at power on.
it would be best to save it first, restart and only after that try for the first time.

**Comment by machinehistories** [comment]
I think it's working, thanks for your help.
